### ISSUE TITLE
Update for ionic 5

### ISSUE THREAD

**Issue by Arieru** [logisticinfotech/ionic4-datepicker#50]
There are UI issues (buttons & footer) when using this plugin in ionic 5 project.
![47T0ugPBmK](https://user-images.githubusercontent.com/14150736/74436884-27f11180-4ea2-11ea-87d9-ba3035e1ef71.png)

**Comment by cybergaala** [comment]
Add this on your global.scss file:

```scss
.li-ionic4-datePicker {
    ion-footer {
        height: 70px!important;
    }
}
```
